import * as Clipboard from "expo-clipboard";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import type { Analysis } from "../api";
import { colors, radius, space } from "../theme";
import { Body, Bullets, Card, Heading, Tag, Tags } from "./ui";

const engagementColor: Record<Analysis["engagement"]["level"], string> = {
  hot: colors.ok,
  warm: colors.ok,
  lukewarm: colors.warn,
  cold: colors.danger,
  unclear: colors.muted,
};

export function ResultView({ result, model, hasConversation }: { result: Analysis; model: string; hasConversation: boolean }) {
  return (
    <View>
      <Card>
        <Heading>The read</Heading>
        <Body>{result.summary}</Body>
        <View style={{ height: space.sm }} />
        <Body muted>{result.confidence_note}</Body>
      </Card>

      {result.caution.length > 0 && (
        <Card style={styles.caution}>
          <Text style={[styles.headingWarn]}>Look out for yourself</Text>
          <Bullets items={result.caution} />
        </Card>
      )}

      <Card>
        <Heading>Likely interests</Heading>
        {result.interests.length ? (
          <>
            <Tags>
              {result.interests.map((i, idx) => (
                <Tag key={idx} label={i.label} tone={i.confidence} />
              ))}
            </Tags>
            <View style={{ height: space.sm }} />
            {result.interests.map((i, idx) => (
              <Text key={idx} style={styles.evidence}>
                {i.label}: {i.evidence}
              </Text>
            ))}
          </>
        ) : (
          <Body muted>Not enough to go on.</Body>
        )}
      </Card>

      <Card>
        <Heading>How engaged they seem</Heading>
        <View style={styles.badge}>
          <Text style={[styles.badgeText, { color: engagementColor[result.engagement.level] }]}>
            {result.engagement.level}
          </Text>
        </View>
        <Bullets items={result.engagement.signals} />
      </Card>

      <Card>
        <Heading>Communication style</Heading>
        <Body>{result.communication_style.description}</Body>
        <Tags>
          {result.communication_style.traits.map((t, idx) => (
            <Tag key={idx} label={t} />
          ))}
        </Tags>
        {result.communication_style.match_tips.length > 0 && (
          <>
            <Text style={styles.subheading}>Matching their style</Text>
            <Bullets items={result.communication_style.match_tips} />
          </>
        )}
      </Card>

      <Card>
        <Heading>{hasConversation ? "What to say next" : "Opener angles"}</Heading>
        {result.opener_angles.map((o, idx) => (
          <Opener key={idx} angle={o.angle} why={o.why_it_fits} example={o.example} />
        ))}
      </Card>

      {result.avoid.length > 0 && (
        <Card>
          <Heading>Probably avoid</Heading>
          <Bullets items={result.avoid} />
        </Card>
      )}

      <Text style={styles.footer}>
        Generated by {model}. These are probability-based estimates about a real person, not facts. Use your own judgment.
      </Text>
    </View>
  );
}

function Opener({ angle, why, example }: { angle: string; why: string; example: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await Clipboard.setStringAsync(example);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  return (
    <View style={styles.opener}>
      <Text style={styles.openerTitle}>{angle}</Text>
      <Text style={styles.openerWhy}>{why}</Text>
      <View style={styles.quote}>
        <Text selectable style={styles.quoteText}>
          {example}
        </Text>
      </View>
      <Pressable onPress={copy} accessibilityRole="button" style={styles.copy}>
        <Text style={styles.copyText}>{copied ? "Copied" : "Copy"}</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  caution: { borderWidth: 1, borderColor: colors.warn },
  headingWarn: { color: colors.warn, fontSize: 18, fontWeight: "700", marginBottom: space.sm },
  subheading: { color: colors.text, fontWeight: "700", fontSize: 15, marginTop: space.md },
  evidence: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: colors.card2,
    borderRadius: radius.pill,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  badgeText: { fontWeight: "700", textTransform: "capitalize" },
  opener: { backgroundColor: colors.card2, borderRadius: 14, padding: space.lg, marginTop: space.md },
  openerTitle: { color: colors.text, fontWeight: "700", fontSize: 16, marginBottom: 4 },
  openerWhy: { color: colors.muted, fontSize: 14, marginBottom: space.sm },
  quote: {
    backgroundColor: colors.bg,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    borderRadius: 8,
    padding: space.md,
  },
  quoteText: { color: colors.text, fontSize: 16, lineHeight: 23 },
  copy: {
    alignSelf: "flex-start",
    marginTop: space.sm,
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: radius.pill,
    paddingVertical: 6,
    paddingHorizontal: 14,
  },
  copyText: { color: colors.accent, fontSize: 13 },
  footer: { color: colors.muted, fontSize: 13, lineHeight: 19, marginBottom: space.xl },
});
